spring:
  application:
    name: bibabo-stock-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        namespace: public
        server-addr: 82.156.216.254:8848
      username: nacos
      password: nacos

    sentinel:
      ## 公司内网，sentinel控制台无法访问推送
      transport:
        port: 8719
        dashboard: 82.156.216.254:9090
      datasource:
        stock-flow:
          nacos:
            server-addr: 82.156.216.254:8848
            data-id: ${spring.application.name}-flow-rules
            username: nacos
            password: nacos
            groupId: BIBABO_SENTINEL_GROUP
            ruleType: flow
        stock-degrade:
          nacos:
            server-addr: 82.156.216.254:8848
            data-id: ${spring.application.name}-degrade-rules
            username: nacos
            password: nacos
            groupId: BIBABO_SENTINEL_GROUP
            ruleType: degrade
    alibaba:
      seata:
        tx-service-group: bibabo_tx_group

  redis:
    redisson:
      config: |
        singleServerConfig:
          address: redis://39.107.156.177:6379
          database: 10
          password: 123456
          subscriptionConnectionPoolSize: 2
          connectionMinimumIdleSize: 2
          connectionPoolSize: 4

  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    initialSize: 2
    maxActive: 5
    maxPoolPreparedStatementPerConnectionSize: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 5
    username: root
    password: 123456
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://82.156.216.254:3306/bibabo_stock?characterEncoding=utf-8&serverTimezone=GMT%2B8
    useGlobalDataSourceStat: true
    validationQuery: SELECT 1 FROM DUAL
  jpa:
    database-platform: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://82.156.216.254:9411
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1

dubbo:
  cloud:
    subscribed-services: bibabo-stock-service
  protocol:
    id: dubbo
    name: dubbo
    port: -1
  scan:
    base-packages: com.bibabo.bibabostockservice
  provider:
    filter: tracing
  consumer:
    filter: tracing

###seata
seata:
  config:
    type: nacos
    nacos:
      server-addr: 82.156.216.254:8848
      group: BIBABO_SEATA_GROUP
      username: nacos
      password: nacos
  #registry:
  #  type: nacos
  #  nacos:
  #    cluster: default
  #    server-addr: 114.116.44.130:8848
  #    group: BIBABO_SEATA_GROUP
  #    username: nacos
  #    password: nacos
  #    application: seata-server

server:
  port: 10087