spring:
  application:
      name: bibabo-stock-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        namespace: public
        server-addr: 114.116.44.130:8848
      username: nacos
      password: nacos

    sentinel:
      ## 公司内网，sentinel控制台无法访问推送
      transport:
        port: 8719
        dashboard: 114.116.44.130:9090
      datasource:
        stock-flow:
          nacos:
            server-addr: 114.116.44.130:8848
            data-id: ${spring.application.name}-flow-rules
            username: nacos
            password: nacos
            groupId: SENTINEL_GROUP
            ruleType: flow
        stock-degrade:
          nacos:
            server-addr: 114.116.44.130:8848
            data-id: ${spring.application.name}-degrade-rules
            username: nacos
            password: nacos
            groupId: SENTINEL_GROUP
            ruleType: degrade

  redis:
    redisson:
      config: |
        singleServerConfig:
          address: redis://39.107.156.177:6379
          database: 10
          password: 123456

dubbo:
  cloud:
    subscribed-services: bibabo-stock-service
  protocol:
    id: dubbo
    name: dubbo
    port: -1
  scan:
    base-packages: com.bibabo.bibabostockservice

