spring:
  application:
    name: bibabo-wdm-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        namespace: public
        server-addr: 114.116.44.130:8848
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    initialSize: 2
    maxActive: 5
    maxPoolPreparedStatementPerConnectionSize: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 5
    username: root
    password: 123456
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://114.116.44.130:3306/bibabo_wdm?characterEncoding=utf-8&serverTimezone=GMT%2B8
    useGlobalDataSourceStat: true
    validationQuery: SELECT 1 FROM DUAL
  jpa:
    database-platform: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  elasticsearch:
    rest:
      uris: http://39.107.156.177:9200
      username: elastic
      password: 123456
  zipkin:
    base-url: http://82.156.216.254:9411
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1

dubbo:
  cloud:
    subscribed-services: bibabo-wdm-service
  protocol:
    id: dubbo
    name: dubbo
    port: -1
  scan:
    base-packages: com.bibabo.bibabowdmservice
  provider:
    filter: tracing
  consumer:
    filter: tracing

canal:
  client:
    instances:
      bibabo:
        host: 39.107.156.177
        port: 11111
        batchSize: 1000
        clusterEnabled: false

logging:
  level:
    com:
      alibaba:
        cloud:
          stream:
            binder:
              rocketmq: DEBUG
          nacos:
            client: debug
server:
  port: 10088