server:
  port: ${random.int[9091,9099]}

spring:
  application:
    name: bibabo-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 114.116.44.130:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        #- id: order
        #  uri: http://localhost:8096/order
        #  predicates:
        #    - Path=/order/**
        #  filters:
        #    - StripPrefix=1
        - id: order
          uri: lb://bibabo-trade
          predicates:
            - Path=/order/**

      #超时
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s

    sentinel:
      transport:
        port: 15000
        dashboard: localhost:8748
      datasource.ds1.file:
        file: "classpath: gateway_order.json"
        ruleType: gw-flow
      scg.fallback:
        mode: response
        response-status: 444
        response-body: 1234
      scg:
        order: -100

  zipkin:
    base-url: http://39.107.156.177:9411
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1

  main:
    allow-bean-definition-overriding: true